services:
  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - ../environments/.development.env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d flashcards-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: pgadmin
    env_file:
      - ../environments/.development.env
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  go-server:
    container_name: go-auth-service
    image: go-server:latest
    env_file:
      - ../environments/.development.env
    build:
      context: ..
      dockerfile: docker/Development.Dockerfile
    ports:
      - "1111:1111"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 1G